from __future__ import annotations
import uuid
from dataclasses import dataclass
from enum import Enum
from typing import List
from algo_trader.src.domain.models import Order, OrderSide, OrderType, PortfolioState
from algo_trader.src.risk.metrics import RiskMetrics


class AlertLevel(str, Enum):
    NORMAL = "NORMAL"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"
    EMERGENCY = "EMERGENCY"


@dataclass
class RiskResult:
    approved: bool
    allowed_quantity: float
    message: str
    alert_level: AlertLevel
    requires_emergency_close: bool = False
    system_lock: bool = False


class RiskManager:
    """
    Pre-trade Risk Interceptor.

    Every order generated by any strategy MUST pass through
    RiskManager.validate_order(order, portfolio_state) before execution.
    """

    def __init__(
        self,
        base_risk_per_trade_jpy: float,
        stop_loss_distance_jpy: float,
        monthly_loss_cap_jpy: float = 30_000.0,
        warning_threshold_jpy: float = 15_000.0,
        critical_threshold_jpy: float = 25_000.0,
    ):
        self.base_risk = base_risk_per_trade_jpy
        self.stop_distance = stop_loss_distance_jpy
        self.cap = monthly_loss_cap_jpy
        self.warning = warning_threshold_jpy
        self.critical = critical_threshold_jpy
        self.metrics = RiskMetrics(monthly_loss_cap_jpy)

    def _is_new_entry(self, order: Order, portfolio: PortfolioState) -> bool:
        """Return True when this order would open a new position."""
        pos = portfolio.positions.get(order.symbol)
        if order.side == OrderSide.BUY:
            return pos is None or pos.side == OrderSide.SELL
        return pos is None or pos.side == OrderSide.BUY

    def _is_exit(self, order: Order, portfolio: PortfolioState) -> bool:
        """Return True when this order reduces an existing position."""
        pos = portfolio.positions.get(order.symbol)
        if pos is None or pos.amount <= 1e-12:
            return False
        return (pos.side == OrderSide.BUY and order.side == OrderSide.SELL) or (
            pos.side == OrderSide.SELL and order.side == OrderSide.BUY
        )

    def _allowable_risk(self, current_loss: float) -> float:
        """
        Allowable_Risk_JPY = min(Base_Risk_Per_Trade, 30000 - Current_Monthly_Cumulative_Loss)
        """
        return min(self.base_risk, self.cap - current_loss)

    def _max_position_size(self, current_loss: float) -> float:
        """
        Max_Position_Size = Allowable_Risk_JPY / Stop_Loss_Distance_JPY
        """
        risk = self._allowable_risk(current_loss)
        if risk <= 1e-12 or self.stop_distance <= 1e-12:
            return 0.0
        return risk / self.stop_distance

    def max_position_size(self, portfolio: PortfolioState) -> float:
        """Public helper: maximum allowed new-entry position size for the current state."""
        loss = portfolio.current_monthly_loss
        size = self._max_position_size(loss)
        if self.warning <= loss < self.critical:
            size *= 0.5
        if loss >= self.critical:
            size = 0.0
        return max(0.0, size)

    def validate_order(self, order: Order, portfolio: PortfolioState) -> RiskResult:
        """Validate an order against the hard loss cap and circuit breakers."""
        current_loss = portfolio.current_monthly_loss
        is_exit = self._is_exit(order, portfolio)

        if current_loss >= self.cap:
            portfolio.system_locked = True
            if is_exit:
                pos = portfolio.positions[order.symbol]
                return RiskResult(
                    approved=True,
                    allowed_quantity=min(order.amount, pos.amount),
                    message="HARD CAP BREACHED. Allowing emergency exit; system will freeze after close.",
                    alert_level=AlertLevel.EMERGENCY,
                    requires_emergency_close=False,
                    system_lock=True,
                )
            return RiskResult(
                approved=False,
                allowed_quantity=0.0,
                message="HARD MONTHLY LOSS CAP BREACHED. SYSTEM LOCKED.",
                alert_level=AlertLevel.EMERGENCY,
                requires_emergency_close=True,
                system_lock=True,
            )

        max_size = self._max_position_size(current_loss)
        alert = AlertLevel.NORMAL

        if current_loss >= self.critical:
            alert = AlertLevel.CRITICAL
            if not is_exit:
                return RiskResult(
                    approved=False,
                    allowed_quantity=0.0,
                    message="CRITICAL circuit breaker: only exit/stop-loss orders allowed.",
                    alert_level=alert,
                    requires_emergency_close=False,
                    system_lock=False,
                )
        elif current_loss >= self.warning:
            alert = AlertLevel.WARNING
            max_size *= 0.5

        if not is_exit and order.amount > max_size:
            return RiskResult(
                approved=False,
                allowed_quantity=max_size,
                message=f"Order size {order.amount} exceeds allowed {max_size:.6f}",
                alert_level=alert,
                requires_emergency_close=False,
                system_lock=False,
            )

        if is_exit:
            pos = portfolio.positions[order.symbol]
            return RiskResult(
                approved=True,
                allowed_quantity=min(order.amount, pos.amount),
                message="Exit order approved",
                alert_level=alert,
                requires_emergency_close=False,
                system_lock=False,
            )

        return RiskResult(
            approved=True,
            allowed_quantity=order.amount,
            message="Order approved by RiskManager",
            alert_level=alert,
            requires_emergency_close=False,
            system_lock=False,
        )

    def generate_emergency_close_orders(self, portfolio: PortfolioState) -> List[Order]:
        """Return market orders required to close every open position."""
        orders: List[Order] = []
        for symbol, pos in portfolio.positions.items():
            close_side = OrderSide.SELL if pos.side == OrderSide.BUY else OrderSide.BUY
            orders.append(
                Order(
                    id=str(uuid.uuid4()),
                    symbol=symbol,
                    side=close_side,
                    order_type=OrderType.MARKET,
                    amount=pos.amount,
                )
            )
        return orders
